# Generated by Django 3.0.7 on 2020-06-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publish_date',
            new_name='published',
        ),
    ]
